WEBUI/Controllers/ContactController.cs
using Project.BLL.DesignPatterns.GenericRepository.ConcRepository;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBUI.Controllers
{
    public class ContactController:Controller
    {
        IssueRepository _iRep;
        MessageRepository _mRep;

        public ContactController()
        {
            _iRep = new IssueRepository();
            _mRep = new MessageRepository();
        }
        public ActionResult AddTechIssue()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddTechIssue(Issue issue)
        {
            _iRep.Add(issue);
            string supportEmail = "We Have Recived your request, we will revert shortly as soon as possible";
            //todo 
            EmailService.Send(issue.Email, body: supportEmail, subject: "TeknoRama Support Team");
            return RedirectToAction("Contact", "Home");
                        
        }
        public ActionResult AddMessage()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMessage(Message message)
        {
            message.MessageType = Project.ENTITIES.Enums.MessageType.Advise;
            _mRep.Add(message);

            string supportEmail = "We Have Recived your request, we will revert shortly as soon as possible";
            EmailService.Send(message.Email, body: supportEmail, subject: "TeknoRama Support Team");
            return RedirectToAction("Contact", "Home");
        }
    }
}

WEBUI/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEBUI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WEBUI/Controllers/ShoppingController.cs
using PagedList;
using Project.BLL.DesignPatterns.GenericRepository.ConcRepository;
using Project.COMMON.Tools;
using Project.ENTITIES.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using WEBUI.AuthenticationClasses;
using WEBUI.Models.ShoppingTools;
using WEBUI.VMClasses;

namespace WEBUI.Controllers
{
    public class ShoppingController:Controller
    {
        OrderRepository _orderRep;
        OrderDetailRepository _orderdetailRep;
        ProductRepository _proRep;
        CategoryRepository _catRep;


        public ShoppingController()
        {
            _proRep = new ProductRepository();
            _catRep = new CategoryRepository();
            _orderdetailRep = new OrderDetailRepository();
            _orderRep = new OrderRepository();
        }
        public ActionResult ShoppingList(int? page, int? categoryID)
        {
            PaginationVM pavm = new PaginationVM
            {
                PagedProducts = categoryID == null ? _proRep.GetActives().ToPagedList(page ?? 1, 9) : _proRep.Where(x => x.CategoryID ==categoryID).ToPagedList(page ?? 1,9),
                Categories=_catRep.GetActives()
            };
            if (categoryID != null) TempData["catID"] = categoryID;
            return View(pavm);
        }

        public ActionResult AddToCart(int id)
        {
            Card card = Session["scart"] == null ? new Card() : Session["scart"] as Card;
            Product productToAdd = _proRep.Find(id);

            CardItem cardItem = new CardItem
            {
                ID = productToAdd.ID,
                Name=productToAdd.ProductName,
                Price = productToAdd.UnitPrice,
                ImagePath = productToAdd.ImangePatch
            };
            card.AddToCard(cardItem);

            Session["count"] = card.ProductCount();
            Session["scart"] = card;

            return RedirectToAction("ShoppingList");

        }

        public ActionResult CardPage()
        {
            if (Session["scart"] != null)
            {
                CardPageVM cpvm = new CardPageVM();
                Card card = Session["scart"] as Card;
               // cpvm.Card = card; //todo
                return View(cpvm);

            }

            TempData["CardIsEmpty"] = "There is no Product in your Basket";
            return RedirectToAction("ShoppingList");
        }

        public ActionResult DeleteFromCard(int id)
        {
            if (Session["scart"]!=null)
            {
                Card card = Session["scart"] as Card;
                card.RemoveFromCard(id);
                Session["count"] = card.ProductCount();

                if(card.MyBasket.Count==0)
                {
                    Session.Remove("scart");
                    TempData["CardIsEmpty"] = "There is no Product in your Basket";
                    return RedirectToAction("ShoppingList");
                }
                return RedirectToAction("CardPage");
            }
            return RedirectToAction("ShoppingList");

        }
        
        public ActionResult ConfirmOrder()
        {
            AppUser currentUser;
            if (Session["member"]!=null)
            {
                currentUser = Session["member"] as AppUser;
            }
            else
            {
                TempData["huest"] = "Please assign to proceed your order";

                return RedirectToAction("RegisterNow", "Register");
            }
            return View();
        }
        //https://localhost:39785/api/Payment/RecievePayment

        [HttpPost]
        public async Task<ActionResult> ConfirmOrderAsync(OrderVM ovm)
        {

            bool result;
            Card card = Session["scart"] as Card;
            ovm.Order.TotalPrice = ovm.PaymentDTO.ShoppingPrice = card.TotalCost;

            // API 

           
            using (HttpClient client = new HttpClient())
            {
                client.BaseAddress = new Uri("https://localhost:39785/api/");

                HttpResponseMessage output;

                try
                {
                    output = await client.PostAsJsonAsync("Payment/ReceivePayment", ovm.PaymentDTO);
                }

                catch (Exception)
                {
                    TempData["connectionDeny"] = "Banka bağlantıyı reddetti";
                    return RedirectToAction("ShoppingList");
                }

                if (output.IsSuccessStatusCode) result = true;
                else result = false;

                if (result)
                {
                    if (Session["member"] != null)
                    {
                        AppUser user = Session["member"] as AppUser;
                        ovm.Order.AppUserID = user.ID;
                        ovm.Order.UserName = user.UserName;
                    }
                    else
                    {
                        ovm.Order.AppUserID = null;
                        ovm.Order.UserName = TempData["anonim"].ToString();
                    }

                    _orderRep.Add(ovm.Order);

                    foreach (CardItem item in card.MyBasket)
                    {
                        OrderDetail od = new OrderDetail();
                        od.OrderID = ovm.Order.ID;
                        od.ProductID = item.ID;
                        od.UnitPrice = item.Price;
                        od.TotalPrice = item.SubTotal;
                        od.Quantity = item.Amount;
                        _orderdetailRep.Add(od);

                        //Stok düşme
                        Product decreaseStock = _proRep.Find(item.ID);
                        decreaseStock.UnitInStock -= item.Amount;
                        _proRep.Update(decreaseStock);
                    }

                    TempData["payment"] = "We have recieved your order";
                    EmailService.Send(ovm.Order.Email, body: $"Your order is proceeded, TotalCost is: ${ovm.Order.TotalPrice}", subject: "Order Succeeded");
                    Session["scart"] = null;
                    Session["count"] = null;
                    return RedirectToAction("ShoppingList");
                }

                else
                {
                    TempData["paymentIssue"] = "There has been a problem of recieveing payment please try again";
                    return RedirectToAction("ShoppingList");
                }
            }

          

        }
        [MemberAuthentication]
        public ActionResult OrderList()
        {
            return View();
        }

    }
}

WEBUI/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WEBUI/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WEBUI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet"
          href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
          crossorigin="anonymous" />
    <title>TEKNOROMA</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">Teknoroma</a>
        <button class="navbar-toggler"
                type="button"
                data-toggle="collapse"
                data-target="#navbarNav"
                aria-controls="navbarNav"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="#">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Contact</a>
                </li>
            </ul>
        </div>
    </nav>
    <div class="container mt-5">
        <h1 class="text-center">Welcome to Teknoroma</h1>
        <p class="text-center">
            It is the Place to Do your best Electronic Shoppings. Teknoroma, with its retail, dealer and alternative sales channels, is one of the few electronic markets in Turkey, consisting of 55 stores, 30 departments, 20 head office personnel and a total of 258 employees, offering many brand options with its wide product range.
        </p>
    </div>
    <div class="hero-buttons spacer">
        <div class="hero-btn">
            <a href="@Url.Action("ShoppingList","Shopping")">
                <button class="bt bt-lg">Start Shopping</button>
            </a>
        </div>
        <div class="hero-btn">
            <a href="@Url.Action("Contact","Home")">
                <button class="bt-secondary">Communication</button>
            </a>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="Please dive in !!"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0C